name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: dgbarreto/stockapp-app/.github/workflows/kmp-module-ci.yml@main
    with:
      module: portfolio
      use-konan-cache: false
    secrets: inherit
